import * as fs from "fs";
import * as path from "path";
import * as vscode from "vscode";
import { resolveFlutterAssetPathContext } from "./flutterAssetPath";
import {
  isFlutterPubspecText,
  readImageStaticConfigFromPubspec,
} from "./pubspecFlutter";

const IMAGE_EXT = new Set([
  ".png",
  ".jpg",
  ".jpeg",
  ".gif",
  ".webp",
  ".svg",
  ".ico",
  ".bmp",
  ".avif",
]);

const DEFAULT_FILE_HEADER =
  "由 Flutter Image Static Generator 生成，请勿手改\nGenerated by Flutter Image Static Generator. Do not edit manually.";

const OUTPUT_CHANNEL = vscode.window.createOutputChannel(
  "Flutter Image Static Generator"
);

function sanitizeIdentifierPart(s: string): string {
  let t = s.replace(/[^\p{L}\p{N}_]+/gu, "_");
  t = t.replace(/_+/g, "_").replace(/^_|_$/g, "");
  if (!t) {
    t = "asset";
  }
  if (/^\d/.test(t)) {
    t = "_" + t;
  }
  return t;
}

function collectImageFiles(dir: string): string[] {
  const out: string[] = [];
  let entries: fs.Dirent[];
  try {
    entries = fs.readdirSync(dir, { withFileTypes: true });
  } catch {
    return out;
  }
  for (const e of entries) {
    const full = path.join(dir, e.name);
    if (e.isDirectory()) {
      out.push(...collectImageFiles(full));
    } else if (e.isFile()) {
      const ext = path.extname(e.name).toLowerCase();
      if (IMAGE_EXT.has(ext)) {
        out.push(full);
      }
    }
  }
  return out;
}

/**
 * 从「图片根目录」向内的相对路径生成标识符片段，不包含根文件夹自身名称（不再出现 images_ 等前缀）。
 */
function buildExportName(imageRoot: string, filePath: string): string {
  const relFile = path.relative(imageRoot, filePath);
  const baseNoExt = sanitizeIdentifierPart(
    path.basename(filePath, path.extname(filePath))
  );
  const segments: string[] = [];
  const relDir = path.dirname(relFile);
  if (relDir && relDir !== "." && !relFile.startsWith("..")) {
    for (const seg of relDir.split(path.sep)) {
      if (seg && seg !== "." && seg !== "..") {
        const p = sanitizeIdentifierPart(seg);
        if (p) {
          segments.push(p);
        }
      }
    }
  }
  if (baseNoExt) {
    segments.push(baseNoExt);
  }
  if (segments.length === 0) {
    return baseNoExt || "asset";
  }
  return segments.join("_");
}

function toPosix(p: string): string {
  return p.split(path.sep).join("/");
}

function escapeTsString(s: string): string {
  return s.replace(/\\/g, "\\\\").replace(/'/g, "\\'");
}

function escapeDartString(s: string): string {
  return s.replace(/\\/g, "\\\\").replace(/'/g, "\\'");
}

/** 将 snake_case 转为 lowerCamelCase，供 Dart 标识符使用 */
function snakeToLowerCamel(s: string): string {
  const parts = s.split("_").filter((p) => p.length > 0);
  if (parts.length === 0) {
    return "asset";
  }
  const head = parts[0].toLowerCase();
  const tail = parts
    .slice(1)
    .map(
      (p) =>
        p.charAt(0).toUpperCase() +
        p.slice(1).toLowerCase().replace(/[^a-zA-Z0-9]/g, "")
    )
    .join("");
  const id = head + tail;
  if (/^\d/.test(id)) {
    return "k" + id.charAt(0).toUpperCase() + id.slice(1);
  }
  return id;
}

const DART_RESERVED = new Set([
  "assert",
  "break",
  "case",
  "catch",
  "class",
  "const",
  "continue",
  "default",
  "do",
  "else",
  "enum",
  "extends",
  "false",
  "final",
  "finally",
  "for",
  "if",
  "in",
  "is",
  "new",
  "null",
  "rethrow",
  "return",
  "super",
  "switch",
  "this",
  "throw",
  "true",
  "try",
  "var",
  "void",
  "while",
  "with",
  "async",
  "await",
  "yield",
  "dynamic",
  "get",
  "set",
  "typedef",
  "required",
  "late",
  "extension",
  "mixin",
  "on",
  "library",
  "import",
  "export",
  "part",
  "of",
  "show",
  "hide",
  "deferred",
  "as",
]);

function dartSafeName(lowerCamel: string): string {
  if (DART_RESERVED.has(lowerCamel)) {
    return lowerCamel + "Path";
  }
  return lowerCamel;
}

/** 易与 Dart 核心类型冲突的类名 */
const DART_CORE_CLASS_NAMES = new Set([
  "String",
  "int",
  "double",
  "bool",
  "num",
  "void",
  "dynamic",
  "Object",
  "Null",
  "Never",
  "Future",
  "Stream",
  "Iterable",
  "List",
  "Set",
  "Map",
  "Record",
  "Error",
  "Exception",
]);

function safeGeneratedClassName(pascal: string): string {
  const lower = pascal.toLowerCase();
  if (
    DART_RESERVED.has(lower) ||
    DART_CORE_CLASS_NAMES.has(pascal) ||
    pascal === "Default" ||
    pascal === "Undefined"
  ) {
    return `${pascal}Paths`;
  }
  return pascal;
}

/**
 * 由输出文件名（去扩展名）得到 PascalCase 类名：去掉特殊符号，按段首字母大写拼接。
 * 例：asset_paths.dart → AssetPaths，image-asset.dart → ImageAsset
 */
function fileBaseToPascalClassName(outputAbsPath: string): string {
  const base = path.basename(outputAbsPath);
  const noExt = base.replace(/\.[^.]+$/i, "");
  const normalized = noExt.replace(/[^\p{L}\p{N}]+/gu, " ").trim();
  const chunks = normalized.split(/\s+/).filter((c) => c.length > 0);
  const parts = chunks.map((c) => {
    const x = c.toLowerCase().replace(/[^a-zA-Z0-9]/g, "");
    if (!x) {
      return "";
    }
    return x.charAt(0).toUpperCase() + x.slice(1);
  }).filter((p) => p.length > 0);
  let name = parts.join("");
  if (!name) {
    name = "GeneratedAssetPaths";
  }
  if (/^\d/.test(name)) {
    name = `N${name}`;
  }
  return safeGeneratedClassName(name);
}

interface GenerateOptions {
  root: string;
  /** 解析 image_folder 时依次尝试的工作区根（含多根工作区）；默认同 [root] */
  imageSearchRoots?: string[];
  imageFolderRel: string;
  outputRel: string;
  pathStyle: string;
  header: string;
}

type GenerateResult =
  | { ok: true; filesCount: number; outputAbs: string }
  | { ok: false; error: string };

/** Flutter 默认输出文件名（当 output_file 表示目录时追加） */
const DEFAULT_OUTPUT_FILE_NAME = "asset_paths.dart";

/**
 * 从 startDir 起按相对路径逐段解析目录；某段大小写与磁盘不一致时仍尝试匹配（Linux 常用）。
 */
function resolvePathSegmentsCaseInsensitive(
  startDir: string,
  relPosix: string
): string | null {
  const parts = relPosix.split("/").filter((p) => p.length > 0);
  if (parts.length === 0) {
    const n = path.normalize(startDir);
    return fs.existsSync(n) && fs.statSync(n).isDirectory() ? n : null;
  }
  let cur = path.normalize(startDir);
  for (const part of parts) {
    if (!fs.existsSync(cur)) {
      return null;
    }
    if (!fs.statSync(cur).isDirectory()) {
      return null;
    }
    let entries: string[];
    try {
      entries = fs.readdirSync(cur);
    } catch {
      return null;
    }
    const exact = path.normalize(path.join(cur, part));
    if (fs.existsSync(exact)) {
      const st = fs.statSync(exact);
      if (st.isDirectory()) {
        cur = exact;
        continue;
      }
      return null;
    }
    const want = part.toLowerCase();
    const found = entries.find((e) => e.toLowerCase() === want);
    if (!found) {
      return null;
    }
    cur = path.normalize(path.join(cur, found));
  }
  return fs.existsSync(cur) && fs.statSync(cur).isDirectory() ? cur : null;
}

/**
 * 将 pubspec 中的 image_folder 解析为磁盘上的图片根目录。
 * - 依次尝试每个工作区根（多根 .code-workspace）。
 * - 子包根 + monorepo 风格 `packages/appAssets/...` → 回退为 `工作区根/assets/...`。
 * - 整段相对路径可做大小写不敏感匹配（便于 Linux）。
 */
function resolveImageRootAbs(
  workspaceRoots: string[],
  imageFolderRel: string
): { abs: string } | { error: string } {
  if (path.isAbsolute(imageFolderRel)) {
    const abs = path.normalize(imageFolderRel.trim());
    if (fs.existsSync(abs) && fs.statSync(abs).isDirectory()) {
      return { abs };
    }
    return { error: `图片目录不存在或不是文件夹：${abs}` };
  }

  const rel = imageFolderRel.trim();
  const forward = rel.replace(/\\/g, "/");
  const attempted: string[] = [];
  const roots =
    workspaceRoots.length > 0
      ? workspaceRoots.map((r) => path.normalize(r))
      : [];

  for (const rootNorm of roots) {
    const primary = path.normalize(path.join(rootNorm, rel));
    attempted.push(primary);
    if (fs.existsSync(primary) && fs.statSync(primary).isDirectory()) {
      return { abs: primary };
    }

    const m = forward.match(/^packages\/([^/]+)\/(.+)$/);
    if (m) {
      const pkgDir = m[1];
      const rest = m[2].replace(/\\/g, "/");
      const base = path.basename(rootNorm);
      const nameMatches =
        base === pkgDir ||
        (process.platform !== "linux" &&
          base.toLowerCase() === pkgDir.toLowerCase());
      if (nameMatches) {
        const alt = path.normalize(path.join(rootNorm, rest));
        attempted.push(alt);
        if (fs.existsSync(alt) && fs.statSync(alt).isDirectory()) {
          return { abs: alt };
        }
        const ciAlt = resolvePathSegmentsCaseInsensitive(rootNorm, rest);
        if (ciAlt) {
          return { abs: ciAlt };
        }
      }
    }

    const ciPrimary = resolvePathSegmentsCaseInsensitive(rootNorm, forward);
    if (ciPrimary) {
      return { abs: ciPrimary };
    }
  }

  const uniq = [...new Set(attempted)];
  return {
    error: `图片目录不存在或不是文件夹。\n配置：image_folder: ${rel}\n已尝试的路径：\n${uniq.join("\n") || "(无)"}\n\n请检查：1) 是否从包含 packages 的仓库根打开，或将该包目录加入「多根工作区」；2) 子包根打开时请改为 image_folder: assets/images；3) Linux 下目录名大小写须与磁盘一致（本扩展已尝试忽略大小写匹配）。`,
  };
}

/**
 * 将 pubspec 中的 output_file 解析为实际文件绝对路径。
 * 支持：具体文件路径；目录（如 ./、lib/gen/、无扩展名的路径）→ 在目录下写入默认 .dart 文件。
 */
function resolveOutputAbs(root: string, outputRel: string): string {
  const trimmed = outputRel.trim();
  const posix = trimmed.replace(/\\/g, "/");

  if (posix === "." || posix === "./") {
    return path.join(root, DEFAULT_OUTPUT_FILE_NAME);
  }

  const abs = path.isAbsolute(outputRel)
    ? path.normalize(trimmed)
    : path.normalize(path.join(root, trimmed));

  if (posix.endsWith("/") || posix.endsWith("/.")) {
    return path.join(abs, DEFAULT_OUTPUT_FILE_NAME);
  }

  let st: fs.Stats | undefined;
  try {
    st = fs.statSync(abs);
  } catch {
    st = undefined;
  }

  if (st?.isDirectory()) {
    return path.join(abs, DEFAULT_OUTPUT_FILE_NAME);
  }

  const base = path.basename(abs);
  const looksLikeFile = /\.(dart|ts|js)$/i.test(base);
  if (!looksLikeFile && !st?.isFile()) {
    return path.join(abs, DEFAULT_OUTPUT_FILE_NAME);
  }

  return abs;
}

function generateStaticCode(opts: GenerateOptions): GenerateResult {
  const { root, imageFolderRel, outputRel, pathStyle, header } = opts;
  const searchRoots =
    opts.imageSearchRoots && opts.imageSearchRoots.length > 0
      ? opts.imageSearchRoots
      : [root];

  const resolvedImage = resolveImageRootAbs(searchRoots, imageFolderRel);
  if ("error" in resolvedImage) {
    return { ok: false, error: resolvedImage.error };
  }
  const imageRoot = resolvedImage.abs;

  const files = collectImageFiles(imageRoot).sort();

  const assetPathCtx = resolveFlutterAssetPathContext(root, imageRoot);

  const outputAbs = resolveOutputAbs(root, outputRel);
  const outputDir = path.dirname(outputAbs);
  fs.mkdirSync(outputDir, { recursive: true });

  const isDart = outputAbs.toLowerCase().endsWith(".dart");
  const className = fileBaseToPascalClassName(outputAbs);

  const used = new Map<string, string>();
  const usedDartIds = new Set<string>();
  const lines: string[] = [];
  if (header.trim()) {
    const h = header.trim();
    if (isDart) {
      for (const hline of h.split("\n")) {
        lines.push(`// ${hline.replace(/^\s*\/\/\s?/, "")}`);
      }
      lines.push("");
    } else if (h.startsWith("/*") || h.startsWith("//")) {
      lines.push(h);
      lines.push("");
    } else {
      lines.push(`/* ${h.replace(/\*\//g, "* /")} */`);
      lines.push("");
    }
  }

  if (isDart) {
    lines.push(`class ${className} {`);
    lines.push(`  ${className}._();`);
  } else {
    lines.push(`export class ${className} {`);
    lines.push("  private constructor() {}");
  }

  let firstAssetLine = true;
  for (const file of files) {
    let exportName = buildExportName(imageRoot, file);
    if (used.has(exportName)) {
      let n = 2;
      while (used.has(`${exportName}_${n}`)) {
        n += 1;
      }
      exportName = `${exportName}_${n}`;
    }
    used.set(exportName, file);

    let value: string;
    if (assetPathCtx.mode === "package") {
      const relPkg = toPosix(
        path.relative(assetPathCtx.packageRoot, file)
      );
      value = `packages/${assetPathCtx.packageName}/${relPkg}`;
    } else if (pathStyle === "relativeWorkspace") {
      value = toPosix(path.relative(root, file));
    } else if (pathStyle === "relativeOutput") {
      value = toPosix(path.relative(outputDir, file));
    } else {
      value = toPosix(path.relative(imageRoot, file));
    }

    if (!firstAssetLine) {
      lines.push("");
    } else if (files.length > 0) {
      lines.push("");
    }
    firstAssetLine = false;

    if (isDart) {
      let dartId = dartSafeName(snakeToLowerCamel(exportName));
      if (usedDartIds.has(dartId)) {
        let n = 2;
        while (usedDartIds.has(`${dartId}${n}`)) {
          n += 1;
        }
        dartId = `${dartId}${n}`;
      }
      usedDartIds.add(dartId);
      lines.push(
        `  static const String ${dartId} = '${escapeDartString(value)}';`
      );
    } else {
      lines.push(
        `  static readonly ${exportName} = '${escapeTsString(value)}';`
      );
    }
  }

  lines.push("}");

  const body = lines.join("\n") + "\n";
  fs.writeFileSync(outputAbs, body, "utf8");

  return { ok: true, filesCount: files.length, outputAbs };
}

export function activate(context: vscode.ExtensionContext): void {
  const watchDisposables: vscode.Disposable[] = [];
  let debounceTimer: ReturnType<typeof setTimeout> | undefined;

  const disposeWatchers = (): void => {
    if (debounceTimer !== undefined) {
      clearTimeout(debounceTimer);
      debounceTimer = undefined;
    }
    for (const d of watchDisposables) {
      d.dispose();
    }
    watchDisposables.length = 0;
  };

  const getGenOptionsFromWorkspace = (): GenerateOptions | null => {
    const folder = vscode.workspace.workspaceFolders?.[0];
    if (!folder) {
      return null;
    }
    const root = folder.uri.fsPath;
    const pubspecPath = path.join(root, "pubspec.yaml");
    if (!fs.existsSync(pubspecPath)) {
      return null;
    }
    const pubCfg = readImageStaticConfigFromPubspec(pubspecPath);
    if ("error" in pubCfg) {
      return null;
    }
    const cfg = vscode.workspace.getConfiguration("flutterImageStaticGenerator");
    const imageSearchRoots = (vscode.workspace.workspaceFolders ?? [folder]).map(
      (w) => w.uri.fsPath
    );
    return {
      root,
      imageSearchRoots,
      imageFolderRel: pubCfg.image_folder,
      outputRel: pubCfg.output_file,
      pathStyle: cfg.get<string>("pathStyle", "relativeWorkspace"),
      header: cfg.get<string>("fileHeader", DEFAULT_FILE_HEADER),
    };
  };

  const runGenerate = (opts: GenerateOptions): GenerateResult => {
    return generateStaticCode(opts);
  };

  const scheduleRegenerate = (reason: string): void => {
    const cfg = vscode.workspace.getConfiguration("flutterImageStaticGenerator");
    if (!cfg.get<boolean>("watch", true)) {
      return;
    }
    const debounceMs = cfg.get<number>("watchDebounceMs", 400);
    if (debounceTimer !== undefined) {
      clearTimeout(debounceTimer);
    }
    debounceTimer = setTimeout(() => {
      debounceTimer = undefined;
      const o = getGenOptionsFromWorkspace();
      if (!o) {
        return;
      }
      const r = runGenerate(o);
      if (r.ok) {
        const rel = toPosix(path.relative(o.root, r.outputAbs));
        OUTPUT_CHANNEL.appendLine(
          `[${new Date().toLocaleTimeString()}] ${reason} → 已写入 ${r.filesCount} 条 (${rel})`
        );
        void vscode.window.setStatusBarMessage(
          `Flutter Image Static: 已更新 ${r.filesCount} 条路径`,
          2500
        );
      } else {
        OUTPUT_CHANNEL.appendLine(
          `[${new Date().toLocaleTimeString()}] ${reason} → 失败：${r.error}`
        );
      }
    }, debounceMs);
  };

  const setupWatchers = (): void => {
    disposeWatchers();
    const folder = vscode.workspace.workspaceFolders?.[0];
    if (!folder) {
      return;
    }
    const cfg = vscode.workspace.getConfiguration("flutterImageStaticGenerator");
    if (!cfg.get<boolean>("watch", true)) {
      return;
    }
    const root = folder.uri.fsPath;
    const pubspecPath = path.join(root, "pubspec.yaml");
    if (!fs.existsSync(pubspecPath)) {
      return;
    }
    let pubspecText: string;
    try {
      pubspecText = fs.readFileSync(pubspecPath, "utf8");
    } catch {
      return;
    }
    if (!isFlutterPubspecText(pubspecText)) {
      return;
    }

    const pubspecWatcher = vscode.workspace.createFileSystemWatcher(
      new vscode.RelativePattern(folder, "pubspec.yaml")
    );
    const onPubspecEvent = (): void => {
      disposeWatchers();
      setupWatchers();
      scheduleRegenerate("pubspec.yaml 变更");
    };
    pubspecWatcher.onDidChange(onPubspecEvent);
    pubspecWatcher.onDidCreate(onPubspecEvent);
    watchDisposables.push(pubspecWatcher);

    const pubCfg = readImageStaticConfigFromPubspec(pubspecPath);
    if ("error" in pubCfg) {
      return;
    }

    const imageFolderRel = pubCfg.image_folder;
    const searchRoots = (vscode.workspace.workspaceFolders ?? [folder]).map(
      (w) => w.uri.fsPath
    );
    const resolvedImg = resolveImageRootAbs(searchRoots, imageFolderRel);
    if ("error" in resolvedImg) {
      return;
    }
    const baseUri = vscode.Uri.file(resolvedImg.abs);

    const imageWatcher = vscode.workspace.createFileSystemWatcher(
      new vscode.RelativePattern(baseUri, "**")
    );
    const onImageEvent = (): void => scheduleRegenerate("图片目录变更");
    imageWatcher.onDidCreate(onImageEvent);
    imageWatcher.onDidChange(onImageEvent);
    imageWatcher.onDidDelete(onImageEvent);
    watchDisposables.push(imageWatcher);
  };

  const folder0 = vscode.workspace.workspaceFolders?.[0];
  if (folder0) {
    const pubspecPath0 = path.join(folder0.uri.fsPath, "pubspec.yaml");
    if (fs.existsSync(pubspecPath0)) {
      try {
        const t = fs.readFileSync(pubspecPath0, "utf8");
        if (isFlutterPubspecText(t)) {
          const cfg0 = vscode.workspace.getConfiguration("flutterImageStaticGenerator");
          if (cfg0.get<boolean>("watch", true)) {
            const initialOpts = getGenOptionsFromWorkspace();
            if (initialOpts) {
              const r0 = runGenerate(initialOpts);
              if (r0.ok) {
                OUTPUT_CHANNEL.appendLine(
                  `[启动] 已生成 ${r0.filesCount} 条 → ${toPosix(path.relative(initialOpts.root, r0.outputAbs))}`
                );
              } else {
                OUTPUT_CHANNEL.appendLine(`[启动] 未生成：${r0.error}`);
              }
            }
            setupWatchers();
          }
        }
      } catch {
        /* ignore */
      }
    }
  }

  context.subscriptions.push(
    vscode.workspace.onDidChangeConfiguration((e: vscode.ConfigurationChangeEvent) => {
      if (!e.affectsConfiguration("flutterImageStaticGenerator")) {
        return;
      }
      disposeWatchers();
      const cfg = vscode.workspace.getConfiguration("flutterImageStaticGenerator");
      if (!cfg.get<boolean>("watch", true)) {
        return;
      }
      const wf = vscode.workspace.workspaceFolders?.[0];
      if (!wf || !fs.existsSync(path.join(wf.uri.fsPath, "pubspec.yaml"))) {
        return;
      }
      try {
        const t = fs.readFileSync(
          path.join(wf.uri.fsPath, "pubspec.yaml"),
          "utf8"
        );
        if (!isFlutterPubspecText(t)) {
          return;
        }
      } catch {
        return;
      }
      setupWatchers();
      scheduleRegenerate("设置变更");
    }),
    new vscode.Disposable(() => disposeWatchers())
  );

  const disposable = vscode.commands.registerCommand(
    "flutterImageStaticGenerator.generate",
    async () => {
      const folder = vscode.workspace.workspaceFolders?.[0];
      if (!folder) {
        vscode.window.showErrorMessage("请先打开一个工作区文件夹。");
        return;
      }
      const root = folder.uri.fsPath;
      const pubspecPath = path.join(root, "pubspec.yaml");
      if (!fs.existsSync(pubspecPath)) {
        vscode.window.showErrorMessage(
          "未找到 pubspec.yaml。本扩展仅支持 Flutter 项目。"
        );
        return;
      }

      const pubCfg = readImageStaticConfigFromPubspec(pubspecPath);
      if ("error" in pubCfg) {
        vscode.window.showErrorMessage(pubCfg.error);
        return;
      }

      const cfg = vscode.workspace.getConfiguration("flutterImageStaticGenerator");
      const imageSearchRoots = (vscode.workspace.workspaceFolders ?? [folder]).map(
        (w) => w.uri.fsPath
      );
      const opts: GenerateOptions = {
        root,
        imageSearchRoots,
        imageFolderRel: pubCfg.image_folder,
        outputRel: pubCfg.output_file,
        pathStyle: cfg.get<string>("pathStyle", "relativeWorkspace"),
        header: cfg.get<string>("fileHeader", DEFAULT_FILE_HEADER),
      };

      const result = runGenerate(opts);
      if (!result.ok) {
        vscode.window.showErrorMessage(result.error);
        return;
      }

      if (result.filesCount === 0) {
        vscode.window.showWarningMessage(
          `在目录中未找到支持的图片文件：${opts.imageFolderRel}`
        );
      }

      const doc = await vscode.workspace.openTextDocument(
        vscode.Uri.file(result.outputAbs)
      );
      await vscode.window.showTextDocument(doc);

      vscode.window.showInformationMessage(
        `已生成 ${result.filesCount} 条路径常量 → ${toPosix(path.relative(root, result.outputAbs))}`
      );
    }
  );
  context.subscriptions.push(disposable, OUTPUT_CHANNEL);
}

export function deactivate(): void {}
